-- Per-tenant SMTP / email settings (optional; fallback to global config.env)
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255) DEFAULT NULL;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS smtp_port INTEGER DEFAULT NULL;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS smtp_use_tls BOOLEAN DEFAULT NULL;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS smtp_user VARCHAR(255) DEFAULT NULL;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS smtp_password VARCHAR(255) DEFAULT NULL;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS email_from VARCHAR(255) DEFAULT NULL;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS email_from_name VARCHAR(255) DEFAULT NULL;
